# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5733aa256cd52ce3a633a6b744436847c5cf3f53f71d48a3429f951a1b41ef8ed1f151714deaf164bd44fd3e9b63df01931aa17cf1e3fcaffabeebf259f1c83

test:
  secret_key_base: 02a8ffbbee8e10534866933330882c2069849c51200e5ce7fcf138642eff9495af6f904ca9cc65773b46bd77dc0d97931f5b201a2c33167060656408968c38b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
